SELECT 
B.codusur VENDEDOR,
D.FORNECEDOR FORNECEDOR,
COUNT(DISTINCT A.CODCLI) POSITIVADO,
SUM(A.QT*A.PUNIT) VALOR
FROM PCMOV A 
JOIN PCUSUARI B ON A.CODUSUR = B.CODUSUR
JOIN PCPRODUT C ON A.CODPROD = C.CODPROD
JOIN PCFORNEC D ON C.CODFORNEC = D.CODFORNEC 


WHERE
A.DTMOV BETWEEN '01-JAN-2023' AND '31-JAN-2023' --'{DATAINI}' AND '{DATAFIN}'
and
B.codsupervisor in (2,8,9)--({SUPERVISOR})

--and B.codusur in ({VENDEDOR})
GROUP BY 
B.codusur,
D.FORNECEDOR 

ORDER BY VENDEDOR, FORNECEDOR

--select *from pcusuari
