SELECT 
-------------------------------------------------------------------------
1 ORD,
-------------------------------------------------------------------------
C.CODSUPERVISOR,
D.NOME SUPERVISOR,
'PLF' CATEGORIA, 
SUM(B.VLVENDAPREV) OBJETIVO_FAT,
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048,120239)
AND
G.CONDVENDA <> 5
),0) REALIZADO,
---------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048,120239)
AND
G.CONDVENDA <> 5
),0)/SUM(B.VLVENDAPREV) PERCENT_ATING,
-------------------------------------------------------------
--=((REALIZADO DIST/DIASCORRIDOS)*DIASUTEIS)/OBJETIVOS
((NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048,120239)
AND
G.CONDVENDA <> 5
),0)/*mud*//19 /*dias corridos*/)*20 /*diasuteis*/)/
SUM(B.VLVENDAPREV) percent_tendencia,
---------------------------------------------------------------
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048,120239)
AND
G.CONDVENDA <> 5
),0)  raf,
-----------------------------------------------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048,120239)
AND
G.CONDVENDA <> 5
),0)/19 MEDIA_DIA,
-------------------------------------------------------
(
SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048,120239)
AND
G.CONDVENDA <> 5
),0)
)/(20-19) MEDIANEC

FROM PCMETA B 
JOIN PCUSUARI C ON B.CODUSUR = C.CODUSUR
JOIN PCSUPERV D ON C.CODSUPERVISOR = D.CODSUPERVISOR
JOIN PCSECAO E ON B.CODIGO = E.CODSEC
WHERE
B.data = (SELECT 
TRUNC(SYSDATE,'MM') FROM DUAL)
AND
B.TIPOMETA = 'S'
AND
D.NOME LIKE '%DANONE%'
AND
E.CODSEC IN (10040,10042,10048,120239)
AND C.CODSUPERVISOR IN 2
GROUP BY C.CODSUPERVISOR,D.NOME
----------------------------------------
UNION
----------------------------------------
SELECT 
-------------------------------------------------------------------------
2 ORD,
-------------------------------------------------------------------------
C.CODSUPERVISOR,
D.NOME SUPERVISOR,
'ADG' CATEGORIA, 
SUM(B.VLVENDAPREV) OBJETIVO_FAT,
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048)
AND
G.CONDVENDA <> 5
),0) REALIZADO,
------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048)
AND
G.CONDVENDA <> 5
),0)/SUM(B.VLVENDAPREV) PERCENT_ATING,
------------------------------------------------------------------
--=((REALIZADO DIST/DIASCORRIDOS)*DIASUTEIS)/OBJETIVOS
((NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048)
AND
G.CONDVENDA <> 5
),0)/*mud*//19 /*dias corridos*/)*20 /*diasuteis*/)/
SUM(B.VLVENDAPREV) percent_tendencia,
---------------------------------------------------------------
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048)
AND
G.CONDVENDA <> 5
),0)  raf,
----------------------------------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048)
AND
G.CONDVENDA <> 5
),0) /19 MEDIA_DIA,
-------------------------------------------------------
(
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC IN (10040,10042,10048)
AND
G.CONDVENDA <> 5
),0)
)/(20-19) MEDIANEC

FROM PCMETA B 
JOIN PCUSUARI C ON B.CODUSUR = C.CODUSUR
JOIN PCSUPERV D ON C.CODSUPERVISOR = D.CODSUPERVISOR
JOIN PCSECAO E ON B.CODIGO = E.CODSEC
WHERE
B.data = (SELECT 
TRUNC(SYSDATE,'MM') FROM DUAL)
AND
B.TIPOMETA = 'S'
AND
D.NOME LIKE '%DANONE%'
AND
E.CODSEC IN (10040,10042,10048)
AND C.CODSUPERVISOR IN 9
GROUP BY C.CODSUPERVISOR,D.NOME
--------------------------------------------------
UNION
-----------------------------------------------------
SELECT 
-------------------------------------------------------------------------
CASE 
WHEN E.CODSEC = 10040 THEN 3
WHEN E.CODSEC = 10042 THEN 4
WHEN E.CODSEC = 10048 THEN 5
WHEN E.CODSEC = 120239 THEN 6
WHEN E.CODSEC = 10046  THEN 7
WHEN E.CODSEC = 10047   THEN 8
WHEN E.CODSEC = 10050   THEN 9
WHEN E.CODSEC = 120387  THEN 10
WHEN E.CODSEC = 6004    THEN 11
WHEN E.CODSEC = 120423  THEN 12
--WHEN E.CODSEC = 10001    THEN 13 --fora de linha
WHEN E.CODSEC = 1005    THEN 14
WHEN E.CODSEC = 1023    THEN 15
WHEN E.CODSEC = 120422  THEN 16
WHEN E.CODSEC = 120424   THEN 17

ELSE 100 END ORD,
-------------------------------------------------------------------------
C.CODSUPERVISOR,
D.NOME SUPERVISOR,
CASE WHEN E.CODSEC = 120424 THEN 'DANILA'
WHEN E.CODSEC = 6004 THEN 'BIVOLT'
WHEN E.CODSEC = 120423 THEN 'DOCES'
WHEN E.CODSEC = 1023 THEN 'SANTA MASSA'
ELSE E.DESCRICAO END CATEGORIA, 
SUM(B.VLVENDAPREV) OBJETIVO_FAT,
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC = E.CODSEC
AND
G.CONDVENDA <> 5
),0) REALIZADO,
----------------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC = E.CODSEC
AND
G.CONDVENDA <> 5
),0)/SUM(B.VLVENDAPREV) PERCENT_ATING,
------------------------------------------------------------------
--=((REALIZADO DIST/DIASCORRIDOS)*DIASUTEIS)/OBJETIVOS
((NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC = E.CODSEC
AND
G.CONDVENDA <> 5
),0)/*mud*//19 /*dias corridos*/)*20 /*diasuteis*/)/
SUM(B.VLVENDAPREV) percent_tendencia,
------------------------------------------------------------------------------
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC = E.CODSEC
AND
G.CONDVENDA <> 5
),0)  raf,
--------------------------------------------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC = E.CODSEC
AND
G.CONDVENDA <> 5
),0)/19 MEDIA_DIA,
-------------------------------------------------------
(
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
I.CODSEC = E.CODSEC
AND
G.CONDVENDA <> 5
),0)
)/(20-19) MEDIANEC
FROM PCMETA B 
JOIN PCUSUARI C ON B.CODUSUR = C.CODUSUR
JOIN PCSUPERV D ON C.CODSUPERVISOR = D.CODSUPERVISOR
JOIN PCSECAO E ON B.CODIGO = E.CODSEC
WHERE
B.data = (SELECT 
TRUNC(SYSDATE,'MM') FROM DUAL)
AND
B.TIPOMETA = 'S'
AND
D.NOME LIKE '%DANONE%'
AND C.CODSUPERVISOR IN 9

GROUP BY C.CODSUPERVISOR, E.DESCRICAO, E.CODSEC,D.NOME

--------------------------------------------------
UNION
-----------------------------------------------------
-----------------------------------------------------
SELECT 
-------------------------------------------------------------------------

18 ORD,
-------------------------------------------------------------------------
C.CODSUPERVISOR,
D.NOME SUPERVISOR,
'TOTAL' CATEGORIA, 
SUM(B.VLVENDAPREV) OBJETIVO_FAT,
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
G.CONDVENDA <> 5
AND
I.CODSEC IN (120423,120387,6004,120424,120422,1005,10040,10042,120239,
                10048,10047,10046,1023,10050)
),0) REALIZADO,
-------------------------------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
G.CONDVENDA <> 5
AND
I.CODSEC IN (120423,120387,6004,120424,120422,1005,10040,10042,120239,
                10048,10047,10046,1023,10050)
),0)/SUM(B.VLVENDAPREV) PERCENT_ATING,
------------------------------------------------------------------
--=((REALIZADO DIST/DIASCORRIDOS)*DIASUTEIS)/OBJETIVOS
((NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
G.CONDVENDA <> 5
AND
I.CODSEC IN (120423,120387,6004,120424,120422,1005,10040,10042,120239,
                10048,10047,10046,1023,10050)
),0)/*mud*//19 /*dias corridos*/)*20 /*diasuteis*/)/
SUM(B.VLVENDAPREV) percent_tendencia,
------------------------------------------------------------------------------
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
G.CONDVENDA <> 5
AND
I.CODSEC IN (120423,120387,6004,120424,120422,1005,10040,10042,120239,
                10048,10047,10046,1023,10050)
),0)    raf,
----------------------------------------------------------------------------------
NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
G.CONDVENDA <> 5
AND
I.CODSEC IN (120423,120387,6004,120424,120422,1005,10040,10042,120239,
                10048,10047,10046,1023,10050)
),0)/19 MEDIA_DIA,
----------------------------------------------------------------------------
(
 SUM(B.VLVENDAPREV) - NVL((SELECT 
SUM(F.QT * F.PVENDA)
FROM 
PCPEDI F 
JOIN PCPEDC G ON F.NUMPED = G.NUMPED
JOIN PCUSUARI H ON F.CODUSUR = H.CODUSUR
JOIN PCPRODUT I ON F.CODPROD = I.CODPROD
WHERE
F.DATA BETWEEN '01-jan-2023' AND '30-jan-2023'
AND
H.CODSUPERVISOR = C.CODSUPERVISOR
AND
G.CONDVENDA <> 5
AND
I.CODSEC IN (120423,120387,6004,120424,120422,1005,10040,10042,120239,
                10048,10047,10046,1023,10050)),0) 
)/(20-19) MEDIANEC
FROM PCMETA B 
JOIN PCUSUARI C ON B.CODUSUR = C.CODUSUR
JOIN PCSUPERV D ON C.CODSUPERVISOR = D.CODSUPERVISOR
JOIN PCSECAO E ON B.CODIGO = E.CODSEC
WHERE
B.data = (SELECT 
TRUNC(SYSDATE,'MM') FROM DUAL)
AND
B.TIPOMETA = 'S'
AND
D.NOME LIKE '%DANONE%'
AND C.CODSUPERVISOR IN 9

GROUP BY C.CODSUPERVISOR,D.NOME


ORDER  BY ORD, SUPERVISOR
